/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.0.0/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)
    id("com.vanniktech.maven.publish") version "0.34.0"

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    signing
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    api(libs.bundles.coroutines)
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use Kotlin Test test framework
            useKotlinTest("2.2.0")
        }
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

mavenPublishing {
    coordinates("io.github.blad3mak3r.snowflake", "core", "$version")

    pom {
        name.set(project.name)
        description.set("Advanced coroutines-based Snowflakes generator")
        url.set("https://github.com/Blad3Mak3r/snowflkae")
        issueManagement {
            system.set("GitHub")
            url.set("https://github.com/Blad3Mak3r/snowflake/issues")
        }
        licenses {
            license {
                name.set("Apache License 2.0")
                url.set("https://github.com/Blad3Mak3r/snowflake/LICENSE.txt")
                distribution.set("repo")
            }
        }
        scm {
            url.set("https://github.com/Blad3Mak3r/snowflake")
            connection.set("https://github.com/Blad3Mak3r/snowflake.git")
            developerConnection.set("scm:git:ssh://git@github.com:Blad3Mak3r/snowflake.git")
        }
        developers {
            developer {
                name.set("Juan Luis Caro")
                url.set("https://github.com/Blad3Mak3r")
            }
        }
    }

    publishToMavenCentral(automaticRelease = true)

    signAllPublications()
}